# Generated by Django 2.0.2 on 2018-05-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publication', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=100)),
                ('date', models.TimeField()),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
    ]
