# Generated by Django 2.0.2 on 2018-05-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
